[package]
name = "sm_test_suite"
version = "0.0.0"
authors = ["Jean Mertz <helloworld@rustic.games>"]
edition = "2018"
publish = false

[dev-dependencies]
sm = { path = "../sm" }
sm_macro = { path = "../sm_macro" }

[dependencies]
compiletest_rs = { version = "*" }
